# Generated by Django 3.1.4 on 2020-12-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20201227_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
